// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package main

import (
	"time"
)

type User struct {
	ID                 int64     `json:"id"`
	Username           string    `json:"username"`
	Email              string    `json:"email"`
	PasswordHash       string    `json:"passwordHash"`
	SecurityQuestion   string    `json:"securityQuestion"`
	SecurityAnswerHash string    `json:"securityAnswerHash"`
	CreatedAt          time.Time `json:"createdAt"`
}
